apiVersion: v1
kind: Pod
metadata:
  name: ibgda-repro
  labels:
    app: ibgda-repro

spec:
  restartPolicy: Never

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: gpu.nvidia.com/model
                operator: In
                values:
                  - H200

  containers:
  - name: ibgda-repro
    image: "quay.io/tms/ibgda-repro:0.0.2"
    imagePullPolicy: Always
    workingDir: /app
    stdin: true
    tty: true
    command: ["/bin/sh","-c"]
    args:
      - |
        sleep infinity
    env:
      - name: CUDA_LAUNCH_BLOCKING
        value: "1"
        # Needed for GDRCOPY to be used.
        # See: https://github.com/NVIDIA/nvidia-container-toolkit/releases/tag/v1.15.0
      - name: NVIDIA_GDRCOPY
        value: "enabled"
      - name: NVIDIA_MOFED
        value: "enabled"

      - name: NCCL_DEBUG
        value: "INFO"
      - name: NVSHMEM_DEBUG
        value: "TRACE"
      - name: NVSHMEM_DEBUG_SUBSYS
        value: "TRANSPORT,INIT,MEM,COLL,BOOTSTRAP"
      - name: NVSHMEM_IB_ENABLE_IBGDA
        value: "true"
      - name: NVSHMEM_REMOTE_TRANSPORT
        value: "ibgda"
#      - name: NVSHMEM_ENABLE_NIC_PE_MAPPING
#        value: "true"
#      - name: NVSHMEM_HCA_LIST
#        value: "mlx5_5"
      - name: NVSHMEM_IB_DISABLE_DMABUF
        value: "true"
      - name: NVSHMEM_BOOTSTRAP_UID_SOCK_IFNAME
        value: "eth0"
      - name: GLOO_SOCKET_IFNAME
        value: "eth0"
      - name: NCCL_SOCKET_IFNAME
        value: "eth0"
      - name: NCCL_IB_HCA
        value: "ibp"
      - name: VLLM_LOGGING_LEVEL
        value: "DEBUG"

    securityContext:
      capabilities:
        add: 
        - "IPC_LOCK"
        - "SYS_RAWIO"
    resources:
      limits:
        memory: 64Gi
        ephemeral-storage: 64Gi
        nvidia.com/gpu: "2"
        rdma/ib: 1
      requests:
        cpu: 8
        memory: 64Gi
        ephemeral-storage: 64Gi 
        nvidia.com/gpu: "2"
        rdma/ib: 1
    volumeMounts:
      - name: dshm
        mountPath: /dev/shm
  volumes:
    # Needed for NCCL to function
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 16Gi
